# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: repo.adeo.no:5443/oppfolging/mininnboks-api
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDay: 20
prometheus:
  enabled: true
  path: /internal/metrics
resources:
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    cpu: 200m
    memory: 512Mi
fasitResources:
  used:
  - alias: appdynamics
    resourceType: applicationproperties

  # stjeler mininnboks-brukeren selv om vi er mininnboks-api
  - alias: srvmininnboks
    resourceType: credential

  - alias: securityTokenService
    resourceType: baseUrl
  - alias: serviceGateway
    resourceType: webservicegateway

  # NB disse webservicene brukes ikke direkte av appen siden vi går gjennom servicegateway,
  # men legger de likevel til for å vise avhegighetsforholdet
  - alias: domene.Brukerdialog:Henvendelse_v2
    resourceType: webserviceendpoint
  - alias: virksomhet:Diskresjonskode_v1
    resourceType: webserviceendpoint
  - alias: virksomhet:Brukerprofil_v3
    resourceType: webserviceendpoint
  - alias: domene.Brukerdialog:SendInnHenvendelse_v1
    resourceType: webserviceendpoint
  - alias: domene.Brukerdialog:InnsynHenvendelse_v1
    resourceType: webserviceendpoint

  # oidc med AzureAD B2C
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: aad_b2c_discovery
    resourceType: baseurl

  # lenker
  - alias: mininnboks.link
    resourceType: baseurl
  - alias: temavelger.link
    resourceType: baseurl
  - alias: brukerprofil.link
    resourceType: baseurl
  - alias: saksoversikt.link
    resourceType: baseurl


webproxy: true
alertProfiles:
  - common-java-modules
