---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mininnboks-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 8080
  ingresses:
  - https://mininnboks-api.nais.oera.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 2400Mi
    requests:
      cpu: 500m
      memory: 2Gi
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/prod/srvmininnboks
      mountPath: /var/run/secrets/nais.io/srvmininnboks-fss
    - kvPath: /serviceuser/data/prod/srvmininnboks-sbs
      mountPath: /var/run/secrets/nais.io/srvmininnboks
    - kvPath: /apikey/appdynamics/prod
      mountPath: /var/run/secrets/nais.io/vault
    - kvPath: /apikey/apigw/prod/pdl-api/mininnboks-api
      mountPath: /var/run/secrets/nais.io/apigw/pdl-api
    - kvPath: /apikey/apigw/prod/security-token-service-token/mininnboks-api
      mountPath: /var/run/secrets/nais.io/apigw/security-token-service-token
    - kvPath: /apikey/apigw/prod/graphql/mininnboks-api
      mountPath: /var/run/secrets/nais.io/apigw/saf-graphql
    - kvPath: /apikey/apigw/prod/rest_hentdokument/mininnboks-api
      mountPath: /var/run/secrets/nais.io/apigw/saf-rest
  tokenx:
    enabled: true
  webproxy: true
  secureLogs:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APP_NAME
      value: "mininnboks-api"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: APP_ENVIRONMENT
      value: "p"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.oera.no/SecurityTokenServiceProvider/"
    - name: STS_TOKENENDPOINT_URL
      value: "https://api-gw.oera.no/security-token-service/rest/v1/sts/token"
    - name: SERVICEGATEWAY_URL
      value: "https://service-gw.oera.no/"
    - name: AAD_B2C_CLIENTID_USERNAME
      value: "45104d6a-f5bc-4e8c-b352-4bbfc9381f25"
    - name: JWKS_URL
      value: "https://navnob2c.b2clogin.com/navnob2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten"
    - name: ISSUER
      value: "https://navnob2c.b2clogin.com/8b7dfc8b-b52e-4741-bde4-d83ea366f94f/v2.0/"
    - name: OPENAM_RESTURL
      value: "https://itjenester.oera.no/esso"
    - name: MININNBOKS_LINK_URL
      value: "https://tjenester.nav.no/mininnboks"
    - name: TEMAVELGER_LINK_URL
      value: "https://www.nav.no/person/kontakt-oss/skriv-til-oss"
    - name: BRUKERPROFIL_LINK_URL
      value: "https://tjenester.nav.no/brukerprofil/"
    - name: SAKSOVERSIKT_LINK_URL
      value: "https://tjenester.nav.no/saksoversikt"
    - name: PDL_API_URL
      value: "https://api-gw.oera.no/pdl-api"
#     Properties nedenfor brukes egentlig ikke. Men appen har en avhengighet mot disse tjenestene via service-gateway.
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_ENDPOINTURL
      value: "https://modapp.adeo.no/henvendelse/services/domene.Brukerdialog/Henvendelse_v2"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/sbl/dialogarena/henvendelse-informasjon-v2/0.6/henvendelse-informasjon-v2-0.6.zip"
    - name: VIRKSOMHET_DISKRESJONSKODE_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_DISKRESJONSKODE_V1_ENDPOINTURL
      value: "https://wasapp.adeo.no/tpsws/Diskresjonskode"
    - name: VIRKSOMHET_DISKRESJONSKODE_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/pip/nav-pip-diskresjonskode-v1-tjenestespesifikasjon/1.2.3/nav-pip-diskresjonskode-v1-tjenestespesifikasjon-1.2.3.zip"
    - name: DOMENE_BRUKERDIALOG_SENDINNHENVENDELSE_V1_ENDPOINTURL
      value: "https://modapp.adeo.no/henvendelse/services/domene.Brukerdialog/SendInnHenvendelse_v1"
    - name: DOMENE_BRUKERDIALOG_SENDINNHENVENDELSE_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/sbl/dialogarena/send-inn-henvendelse/0.3/send-inn-henvendelse-0.3.zip"
    - name: DOMENE_BRUKERDIALOG_SENDINNHENVENDELSE_V1_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_INNSYNHENVENDELSE_V1_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_INNSYNHENVENDELSE_V1_ENDPOINTURL
      value: "https://modapp.adeo.no/henvendelse/services/domene.Brukerdialog/InnsynHenvendelse_v1"
    - name: DOMENE_BRUKERDIALOG_INNSYNHENVENDELSE_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/sbl/dialogarena/innsyn-henvendelse/0.3/innsyn-henvendelse-0.3.zip"
    - name: CXF_SECURE_LOG
      value: "enabled"
    - name: RATE_LIMITER_URL
      value: "http://rate-limiter.personoversikt.svc.nais.local"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api"
    - name: SAF_API_URL
      value: "https://api-gw.oera.no/safselvbetjening"
    - name: SAF_CLIENT_ID
      value: "prod-fss:teamdokumenthandtering:safselvbetjening"